spring:
  cloud:
    gcp:
      pubsub:
        project-id: local
        emulator-host: localhost:9808

management:
  health:
    pubsub:
      enabled: false

logging:
  level:
    uk.gov.ons.ctp: INFO
    org.springframework: INFO

case-service-settings:
  rest-client-config:
    port: 8162        

dummy-user-config:
  allowed: false
  user-id: 46e62d6a-479c-11ec-aab4-4c3275913db5
  user-identity: philip.whiles@ext.ons.gov.uk
