logging:
  level:
    uk.gov.ons.ctp.integration.contactcentresvc: INFO
    uk.gov.ons.ctp.common: INFO
    org.springframework: OFF
  profile: CLOUD

cloud:
  gcp:
    pubsub:
      subscriber:
        flow-control:
          max-outstanding-element-count: 100

dummy-user:
  allowed: false