logging:
  level:
    uk.gov.ons.ctp.integration.contactcentresvc: DEBUG
    uk.gov.ons.ctp.common: DEBUG
    org.springframework: WARN
  profile: CLOUD

cloud:
  gcp:
    pubsub:
      subscriber:
        flow-control:
          max-outstanding-element-count: 100
  
dummy-user:
  allowed: false