logging:
  level:
    uk.gov.ons.ctp.integration.contactcentresvc: INFO
    uk.gov.ons.ctp.common: INFO
    org.springframework: WARN
  profile: CLOUD

management:
  metrics:
    export:
      stackdriver:
        enabled: true

cloud:
  gcp:
    pubsub:
      subscriber:
        flow-control:
          max-outstanding-element-count: 100
