package uk.gov.ons.ctp.integration.contactcentresvc.model;

public enum CaseSubInteractionType {
  CALL_NUMBER_ENGAGED,
  CALL_NUMBER_UNOBTAINABLE,
  CALL_ANSWERED,
  CALL_UNANSWERED,
  CALL_VOICEMAIL,

  FULFILMENT_PRINT,
  FULFILMENT_SMS,
  FULFILMENT_EMAIL,

  REFUSAL_HARD_REFUSAL,
  REFUSAL_EXTRAORDINARY_REFUSAL,
  REFUSAL_SOFT_REFUSAL,
  REFUSAL_WITHDRAWAL_REFUSAL
}
