package uk.gov.ons.ctp.integration.contactcentresvc.model;

public enum PermissionType {
  SUPER_USER,
  SEARCH_CASES,
  VIEW_CASE,
  REFUSE_CASE,
  REMOVE_CASE,
  INVALIDATE_CASE,
  MODIFY_CASE,
  LAUNCH_EQ,
  CALL_RESPONDENT_ADHOC,
  CALL_RESPONDENT_PRIORITISED,
  CALL_RESPONDENT_SCHEDULED,
  REQUEST_SMS_FULFILMENT,
  REQUEST_POSTAL_FULFILMENT,
  REQUEST_EMAIL_FULFILMENT,
  ADD_CASE_INTERACTION
}
