ALTER TABLE case_response RENAME TO uac;

ALTER TABLE uac DROP COLUMN cohort;
ALTER TABLE uac DROP COLUMN responded;

ALTER TABLE uac ADD COLUMN active BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE uac ADD COLUMN receipt_received BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE uac ADD COLUMN eq_launched BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE uac ADD COLUMN uac_hash TEXT NOT NULL DEFAULT '';
ALTER TABLE uac ADD COLUMN questionnaire TEXT NOT NULL DEFAULT '';
ALTER TABLE uac ADD COLUMN active BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE uac ADD COLUMN collectionExerciseId uuid NOT NULL DEFAULT false;
ALTER TABLE uac ADD COLUMN surveyId uuid NOT NULL DEFAULT false;
ALTER TABLE uac ADD COLUMN collectionInstrumentUrl TEXT NOT NULL DEFAULT '';

ALTER TABLE uac ALTER COLUMN active DROP DEFAULT;
ALTER TABLE uac ALTER COLUMN receipt_received DROP DEFAULT;
ALTER TABLE uac ALTER COLUMN eq_launched DROP DEFAULT;
ALTER TABLE uac ALTER COLUMN uac_hash DROP DEFAULT;
ALTER TABLE uac ALTER COLUMN questionnaire DROP DEFAULT;
ALTER TABLE uac ALTER COLUMN collectionExerciseId DROP DEFAULT;
ALTER TABLE uac ALTER COLUMN surveyId DROP DEFAULT;
ALTER TABLE uac ALTER COLUMN collectionInstrumentUrl DROP DEFAULT;

ALTER TABLE collection_case ADD COLUMN cc_status TEXT NOT NULL DEFAULT '';
ALTER TABLE collection_case ALTER COLUMN cc_status DROP DEFAULT;


